### ISSUE TITLE
Comment in the last chapter

### ISSUE THREAD

**Issue by FrankHB** [The-Orizon/utf8everywhere#13]
Though there are some other technical(ly-biased) issues, it seems the comment in the last chapter should be solely responded here - as a sentence right after endorsement of Unicode, it suggests GB18030 is not Unicode-ish, which is not true.

Since the original text does mention UTF-16 as "Unicode", it is not likely to be misinterpreted; but the situation is different for GB18030.

(Moreover, you'd better help readers to know why GB18030, as an encoding standard being mandated by the Chinese government, is superseded by UTF-8 in your cases.)

See also [here](https://gist.github.com/FrankHB/00731fedf07b4ea271afa70a5cdc8d9d#13).

**Comment by m13253** [comment]
> it suggests GB18030 is not Unicode-ish, which is not true.

GB18030 is indeed a Unicode Transformation Format (UTF), despite the fact that the keyword "UTF" is missing from its name.
I carefully checked the utf8everywhere.org article and did not find any mistake on the definitions. The point of this manifesto is "UTF-8 everywhere" instead of "Unicode everywhere". The use of UTF-8, instead of UTF-16 or GB18030 is encouraged while no conflict arise when we talk about whether GBK or GB18030 are UTFs.

> Since the original text does mention UTF-16 as "Unicode"

Please be cautious about these two terms: "encoding" and "charset": UTF-16 is an encoding, aka a Unicode Transformation Format (UTF), while Unicode is a charset. All UTFs are encodings, including GB18030, which fits in both categories.
The utf8everywhere.org original text already clarified that "UTF-16 as Unicode" is wrong: "UTF-16 encoding (often mistakenly referred to as ‘widechar’ or simply ‘Unicode’ in the Windows world)"

> (Moreover, you'd better help readers to know why GB18030, as an encoding standard being mandated by the Chinese government, is superseded by UTF-8 in your cases.)

We are a translation project. Since we are not the authors of this article, we did not plan to append too much words. And the world would welcome if you could contribute an article about GB18030.
For reference, I will list out some facts about GB18030:
- Both UTF-8, UTF-16, UTF-32, GB18030 are UTFs, and support up to (0x10ffff - 0x800 = 0x10f7ff) codepoints.
- Both UTF-8, UTF-16, UTF-32, GB18030 will take up to 4 bytes to store a Unicode codepoint.
- There is no simple algorithm to convert between GB18030 to Unicode codepoint value. A program might need to carry several KiBs of conversion table.
- GB18030 is not only an encoding and a charset, but also a glyph set. That means it defines the glyph, making it [unacceptable for users outside mainland China](http://blog.justfont.com/2014/01/that-is-not-tw-standard/). While UTF-8, UTF-16, UTF-32 are only encodings — they are not charsets or glyph sets, making them available internationally.
- 24 Chinese characters are mapped to PUA [["L2/06-394 Update on GB 18030:2005"](http://www.unicode.org/L2/L2006/06394-gb18030-2005.txt)], breaking compatibility to GB2312/GBK and Unicode standard, forcing [more lines of code](https://github.com/The-Orizon/nlputils/blob/master/gbk_pua.py) to be written to handle this problem.
- The second byte of GBK/GB18030 encoding could be `"`, `'`, `\`, forcing software vendors take extra security considerations for escaping and injection preventing. This is the same for other EUC encodings such as BIG5 and Shift-JIS, though Shift-JIS does not even have a `\` character.

> See also here.

Thank you for your comments and :%s/.*/\[citation needed\]/g^M. Have a nice day.

**Comment by FrankHB** [comment]
Great points, though they still do not constitute an exhausted list, e.g. missing `O(1)` random access by offset in a long string with mojibake prevented (in a predictable way, at least). Besides that, I actually also prefer UTF-8 to GB18030 in general (as external transformation formats) for similar reasons you've mentioned. Well, although almost all of these points (except for the code you linked) are things I have known previously, most of them are not obvious enough to average readers. Since the article is to promote a single encoding scheme which should ideally have more extraordinary benefits than all competitors, it could do better on that. (But anyway, as you said, I'd comment on the original article, rather than the translation here.)

BTW, I posted my link as a loose reference for the related topics, not only for this issue. That said, I initially thought it a good introduction of these topics for novices, but then I was disappointed (and a bit unhappy) by the technical wrongs and value judgements embedded in the original article. I'd certainly complete some errata someday, but it would be in the draft state (read: in a bunch of long long TODO gists w/o many citations) for a long time. I bet I'll have a nice day then :)

**Comment by FrankHB** [comment]
One more clarification: I should have use more precise terminology to express the issue. My fault on "UTF-16 as Unicode".

However, to attribute UTF-16 as a form of Unicode is not wrong, since Unicode itself is not used only as a name of some variants of charset. (And as I've suggested, this umbrella term is less valuable when only used as a charset).

Please also note, the mess of terminology is also not merely the fault of Windows guys. The "widechar" is also quite accurate with some common assumptions (even less than ones in the original article). As comparison, there are cases where `wchar_t` is implemented as octet (notably, in Android's original Bionic), even it sounds like kidding (`CHAR_BIT` is required to be at least `8`, so `wchat_t` will not be wider than anything like character types...)

If the charset is intended to be emphasized, I prefer the (probably only) technically correct term: _UCS_.

As of referring to the standard specifying the charset in formal cases, I prefer _ISO/IEC 10646_ as possible, which keeps away any hopelessly potential brand-name-like issues on "Unicode"™. (In fact, Unicode® may be registed somewhere in the name of "Unicode, Inc.".)
